id: I3B94A5A4
legacy_id: P010491
ocr_import_info:
  bdrc_scan_id: W2PD17504
  source: bdrc
  ocr_info:
    timestamp: '2020-03-27T07:46:42'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-03T10:19:39.702649+00:00'
last_modified: 2022-09-03 18:19:46.950464
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W2PD17504
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW2PD17504
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: སྨིན་གླིང་སྒྲུབ་ཐབས་འདོད་འཇོའི་བུམ་བཟང་གི་ཙཀླི།
statistics:
  ocr_word_mean_confidence_index: 0.8706607581547875
  ocr_word_median_confidence_index: 0.9700000286102295
quality: null
bases:
  I4PD1466:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4PD1466
      total_pages: 198
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I4PD1466.txt
    statistics:
      ocr_word_median_confidence_index: 0.9700000286102295
      ocr_word_mean_confidence_index: 0.9004280571511969
    legacy_id: v001
  I4PD1467:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4PD1467
      total_pages: 53
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I4PD1467.txt
    statistics:
      ocr_word_median_confidence_index: 0.9700000286102295
      ocr_word_mean_confidence_index: 0.8097390539645594
    legacy_id: v002
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
