id: I3B94A5A4
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T07:47:06+00:00'
last_modified: '2022-06-08T13:59:29.988637+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W2PD17504
  title: "སྨིན་གླིང་སྒྲུབ་ཐབས་འདོད་འཇོའི་བུམ་བཟང་གི་ཙཀླི། \n"
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '4697':
      image_group_id: I4PD1466
      title: ''
      total_pages: 198
      order: 1
      base_file: 4697.txt
    '8181':
      image_group_id: I4PD1467
      title: ''
      total_pages: 53
      order: 2
      base_file: 8181.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
